import Head from "next/head";
import { Prompt } from "next/font/google";
import styles from "@/styles/KnowUs.module.css";
import Image from "next/image";

const prompt = Prompt({
  subsets: ["latin"],
  weight: "400",
});

function KnowUs() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main1}>
        <div className={styles.knowUSContainer}>
          <div className={styles.knowUSContainer__logo}>
            <h1 className={styles.knowUSContainer__logo__h1}>Conóceme</h1>
            <br />
            <Image
              src="https://res.cloudinary.com/df4snwy5t/image/upload/v1681323335/1_ctzf5i.png"
              alt="img logo"
              width={500}
              height={300}
            />
          </div>
          <div className={styles.knowUSContainer__text}>
            <div className={prompt.className}>
              <p className={styles.knowUSContainer__text__p1}>
                Somos una empresa dedicada a la importación y exportación de
                productos de alta calidad para el mundo de Audio, Video,
                Iluminación en el sector de espectáculos, eventos en vivo y
                teatral. Nos enfocamos en la distribución directa. Estamos
                comprometidos con ofrecer soluciones innovadoras y tecnológicas
                para crear experiencias únicas y memorables. Nuestro objetivo es
                brindar productos de calidad superior que superen las
                expectativas de nuestros clientes en todo momento.
              </p>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}

export default KnowUs;
