import Head from "next/head";
import { Prompt } from "next/font/google";
import styles from "@/styles/Banner.module.css";
import Link from "next/link";
import Image from "next/image";
import { BsFacebook, BsTwitter, BsInstagram } from "react-icons/bs";

const prompt = Prompt({
  subsets: ["latin"],
  weight: "400",
});

function Header() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.bannerContainer}>
          <div className={styles.bannerContainer__Navbar}>
            <div className={styles.bannerContainer__NavbarLogo}>
              <Image
                src="https://res.cloudinary.com/df4snwy5t/image/upload/v1681261516/NEGRO_FONDO_BLANCO_LINEA_1_y7r0gp.png"
                alt="img logo"
                width={200}
                height={100}
              />
            </div>
            <div className={styles.bannerContainer__NavbarOptions}>
              <p>Productos</p>
              <p>Compañia</p>
              <p>Marcas Asociadas</p>
            </div>
          </div>
          <div className={styles.bannerContainer__banner}>
            <div className={styles.v_line1}></div>
            <div className={styles.bannerContainer__bannerText}>
              <div className={prompt.className}>
                <h1 className={styles.bannerContainer__bannerText__h1}>
                  Compañia lider <br />
                  en luminaria
                </h1>
              </div>
              <p className={styles.bannerContainer__bannerText__p1}>
                Somos una compañia lder en el mercado del desarrollo web e
                integraciod <br /> de herrramientas de de nueva generacion para
                la optimizacion
              </p>
              <p className={styles.bannerContainer__bannerText__p2}>
                Somos una compañia lder en el mercado del desarrollo web e
                integraciod <br /> de herrramientas de de nueva generacion para
                la optimizacion
              </p>
            </div>
            <div className={styles.bannerContainer__bannerImg}>
              <Image
                src="https://res.cloudinary.com/df4snwy5t/image/upload/v1681329988/256_gdz4e1.png"
                alt="background banner"
                layout="resposive"
                width={500}
                height={400}
              />
            </div>
            <div className={styles.v_line}></div>
            <div className={styles.icons_redes}>
              <BsInstagram />
              <BsFacebook />
              <BsTwitter />
            </div>
          </div>
        </div>
      </main>
    </>
  );
}

export default Header;
